3.Compute outer product of 2 vectors.

In [1]:
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]
print("original matrix:")
print(p)
print(q)
result=np.outer(p,q)
print("Outer product of the two vectors")
print(result)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the two vectors
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


5.write a numpy program to compute the sum of the diagonal element of a given array(matrix).

In [8]:
import numpy as np
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original matrx")
print(m)
result=np.trace(m)
print("trace of the matrx:")
print(result)

original matrx
[[1 2 3]
 [4 5 6]
 [7 8 9]]
trace of the matrx:
15


4.Write a numpy program to compute the condition number of a given matrix

In [10]:
import numpy as np
m=np.array([[1,2],[3,4]])
print("original matrx")
print(m)
result=np.linalg.cond(m)
print("condition number of the matrx:")
print(result)

original matrx
[[1 2]
 [3 4]]
condition number of the matrx:
14.933034373659268
